package org.openxdata.proto;

import java.util.List;
import java.util.Map;

import org.openxdata.proto.model.OxdWorkitem;

/**
 * A {@link SubmissionContext} that supports use of {@link OxdWorkitem}
 * 
 * These {@link OxdWorkitem}s are generated from workitems that come from external Systems or Workflow engines.
 * 
 */
public interface WFSubmissionContext extends GenericSubmissionContext {

	/**
	 * A workitem has a set of parameters that need to be filled with answers from a given oxd question.
	 * 
	 * Which means each parameter in a workitem needs to be mapped to a given question in a form.
	 * 
	 * This method returns that parameter to question map.
	 * 
	 * @param formId
	 *            the formDef id
	 * @param caseId
	 *            unique identifier for the workitem
	 * @return parameter to question map, empty map if no map is present
	 */
	public Map<String, String> getOutParamsQuestionMapping(int formId, String caseId);

	/**
	 * Returns the workitem given the unique Id. This Unique ID is usually generated by the workitem engine returns null
	 * if none
	 */
	public OxdWorkitem getWorkitem(String workitemId);

	/**
	 * Gets all workitems for the specified ids
	 * 
	 * @param workitemIds
	 * @return list of {@link OxdWorkitem}s
	 */
	public List<OxdWorkitem> getWorkItems(String... workitemIds);

	/**
	 * 
	 * Submits the workitem data back to the workflow engine.
	 * 
	 * The workitem data xml should be in the format
	 * 
	 * @param workitemId
	 * @param workitemDataXml
	 *            The data to be passed back into the workitem.
	 * 
	 *            <data> <param_variable> DATA1 </param_variable> <param_variable2> DATA1 </param_variable2> </data>
	 */
	public void submitWorkitem(String workitemId, String workitemDataXml);

	/**
	 * Gets all the available workitems assigned to the currently logged in user and have not yet been executed or
	 * completed.Implemetations of this method should make sure that the workitems returned do not contain forms that
	 * the currently logged in user is not mapped to.
	 * 
	 * @return all available workitems assigned to the currently logged in user
	 */
	public List<OxdWorkitem> availableWorkitems();

	/**
	 * Disables a workitem so that it is never returned back when the {@link #availableWorkitems()} method is called.
	 * 
	 * @param workitemId
	 *            the workitem id to disable
	 */
	public void disableWorkitem(String workitemId);

}
